### ISSUE TITLE
Add additional resources in other languages

### ISSUE THREAD

**Issue by wbuchanan** [mstaniak/autoEDA-resources#2]
# Stata Packages

## Conference Presentations
https://wbuchanan.github.io/stataConference2018/

## Libraries
https://github.com/wbuchanan/eda

Until I have more availability the package relies on LaTeX to produce a pdf with all permutations of univariate and bivariate graphs and tables of summary statistics; there are also a couple instances of plots that use three variables (weighted scatter plots to be specific).  The package started being developed several years ago and is the only package of its type in the Stata environment that I am aware of and takes a very different approach compared to many other libraries available.

**Comment by mstaniak** [comment]
Added, thank you very much
